version: "3"

services:
  data-mapper:
    build:
      dockerfile: data-mapper/Dockerfile
      context: .
    volumes:
      - data-share:/src/vol
    healthcheck:
      test: ["CMD-SHELL", "test -f /src/vol/healthcheck.txt"]
      interval: 5s
      retries: 10
      start_period: 20s
      timeout: 1s
    command: ["python3", "mapper.py"]

  png-mapper:
    build:
      dockerfile: png-mapper/Dockerfile
      context: .
    volumes:
      - type: bind
        source: ./
        target: /src
      - data-share:/src/vol
    entrypoint: /bin/sh
    depends_on: 
      data-mapper:
        condition: service_healthy
    command: ["-c", "whoami && cd /src/png-mapper/ && sh ./build.sh"]
volumes:
    data-share:
