version: "3"

services:
  data-mapper:
    build:
      dockerfile: data-mapper/Dockerfile
      context: .
    volumes:
      - type: volume
        source: data-share
        target: /src/data-vol
#    healthcheck:
#      test: ["CMD-SHELL", "test -f /src/data-vol/healthcheck.txt"]
#      interval: 5s
#      retries: 10
#      start_period: 300s
#      timeout: 1s
    command: ["python3", "mapper.py"]

  png-mapper:
    build:
      dockerfile: png-mapper/Dockerfile
      context: .
    volumes:
      - type: bind
        source: ./
        target: /base/images
      - type: volume
        source: data-share
        target: /src/vol
    entrypoint: /bin/sh
#    depends_on: 
#      data-mapper:
#        condition: service_healthy
    command: ["-c", "whoami && cd /src/ && sh ./build.sh"]
volumes:
    data-share:
